[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/v1/*"
  to = "http://13.205.128.239/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
